name: transport_website
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter_lints:
  firebase_core:
  firebase_storage:
  cloud_firestore:
  flutter_iconly:
  lottie: ^3.1.0
  flutter_staggered_grid_view: 
  get_storage:
  intl: ^0.19.0
  flutter_svg: ^2.0.16
  # carousel_slider: ^5.0.0
  video_player: ^2.8.1 # Güncel versiyonu kontrol edin
  # chewie: ^1.7.0      # Güncel versiyonu kontrol edin
  animate_do:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/fonts/
    - assets/videos/
    - assets/icons/
    - assets/lottie/
    - assets/image/
    - assets/logos/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
  uses-material-design: true
  generate: true